<a href="https://colab.research.google.com/github/techshot25/SATscores/blob/master/SATscores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SAT scores
### By Ali J. Shannon


---

In this project, I am writing a software that predicts the SAT Reading score from the Math and Writing portions using a simple linear regression.


---

Data for this project are retrieved from https://www.kaggle.com/spscientist/students-performance-in-exams

In [1]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# from sklearn import preprocessing

# for splitting our data into training and testing sets
from sklearn.model_selection import train_test_split

# using pandas to read the excel file as a dataset
df = pd.read_csv('StudentsPerformance.csv')


df[df.columns[5:8]]

     math score  reading score  writing score
0            72             72             74
1            69             90             88
2            90             95             93
3            47             57             44
4            76             78             75
5            71             83             78
6            88             95             92
7            40             43             39
8            64             64             67
9            38             60             50
10           58             54             52
11           40             52             43
12           65             81             73
13           78             72             70
14           50             53             58
15           69             75             78
16           88             89             86
17           18             32             28
18           46             42             46
19           54             58             61
20           66             69             63
21           65             75             70
22           44             54             53
23           69             73             73
24           74             71             80
25           73             74             72
26           69             54             55
27           67             69             75
28           70             70             65
29           62             70             75
..          ...            ...            ...
970          89            100            100
971          78             72             69
972          53             50             60
973          49             65             61
974          54             63             67
975          64             82             77
976          60             62             60
977          62             65             58
978          55             41             48
979          91             95             94
980           8             24             23
981          81             78             78
982          79             85             86
983          78             87             91
984          74             75             82
985          57             51             54
986          40             59             51
987          81             75             76
988          44             45             45
989          67             86             83
990          86             81             75
991          65             82             78
992          55             76             76
993          62             72             74
994          63             63             62
995          88             99             95
996          62             55             55
997          59             71             65
998          68             78             77
999          77             86             86

[1000 rows x 3 columns]

In [0]:
# first we will use linear regression to predict writing scores
X = df[df.columns[5:7]].values
y = df[df.columns[7]].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression

linreg = LinearRegression().fit(X_train, y_train)

linreg.score(X_test,y_test)

0.9103951004294347

So far, this has a pretty decent score. This model can be used to predict writing scores with about 91% accuracy.

In [0]:
# transform strings to numerical values for use with DecisionTreeClassifier
#df = df.apply(preprocessing.LabelEncoder().fit_transform)

#y = df['parental level of education'].values
#X = df.drop(['parental level of education','gender','race/ethnicity','lunch','test preparation course'], axis=1).values

In [0]:
#print(X)

#X_train, X_test, y_train, y_test = train_test_split(
#    X, y, test_size=0.2, random_state=42)

In [0]:
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.tree import DecisionTreeClassifier

#knn = KNeighborsClassifier().fit(X_train, y_train)
#dtc = DecisionTreeClassifier().fit(X_train, y_train)

#print(accuracy_score(y_test, knn.predict(X_test)))
#print(accuracy_score(y_test, dtc.predict(X_test)))